server:
  applicationConnectors:
    - type: http
      port: 8880
  adminConnectors:
    - type: http
      port: 8881

testMode: true
cacheDuration: 10 seconds

proxyClientConfig: 
   connectionTimeout : 4 seconds
   timeout : 4 seconds